NewsPaper/NewsPaper/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('posts/', include('news.urls'))
]

NewsPaper/news/urls.py
from django.urls import path
from .views import PostsList, PostDetail, PostDetailView, PostCreateView, PostUpdateView, PostDeleteView

app_name = 'news'
urlpatterns = [
    path('', PostsList.as_view()),
    path('<int:pk>', PostDetail.as_view(), name='products'),
    path('post/<int:pk>/', PostDetailView.as_view(), name='post_detail'),
    path('post/create/', PostCreateView.as_view(), name='post_create'),
    path('post/update/<int:pk>/', PostUpdateView.as_view(), name='post_update'),
    path('post/delete/<int:pk>/', PostDeleteView.as_view(), name='post_delete'),
]

NewsPaper/news/models.py
from django.db import models
from django.contrib.auth.models import User
from django.db.models import Sum

class Author(models.Model):
    rating = models.SmallIntegerField(default=0)
    authorUser = models.OneToOneField(User, on_delete=models.CASCADE)

    def update_rating(self):
        postRat = self.post_set.all().aggregate(postRating=Sum('rating'))
        pRat = 0
        pRat += postRat.get('postRating')

        commentRat = self.authorUser.comment_set.all().aggregate(commentRating=Sum('rating'))
        cRat = 0
        cRat += commentRat.get('commentRating')

        self.rating = pRat * 3 + cRat
        self.save()

class Category(models.Model):
    categoryName = models.CharField(max_length=64, unique=True)

class Post(models.Model):

    article = 'AT'
    news = 'NW'

    ARTICLE_OR_NEWS = [
        (article, 'Статья'),
        (news, 'Новость'),
    ]
    author = models.ForeignKey(Author, on_delete=models.CASCADE)
    type = models.CharField(max_length=2,
                                choices=ARTICLE_OR_NEWS,
                                default=article)
    createData = models.DateTimeField(auto_now_add=True)
    postCategory = models.ManyToManyField(Category, through='PostCategory')
    title = models.CharField(max_length = 128)
    articleText = models.TextField()
    rating = models.SmallIntegerField(default=0)
    description = models.TextField()

    def like(self):
        self.rating = self.rating + 1
        self.save()

    def dislike(self):
        self.rating = self.rating - 1
        self.save()

    def preview(self):
        return self.articleText[:123] + '...'

    def get_absolute_url(self):
        return f'/posts/{self.id}'

class PostCategory(models.Model):
    postTr = models.ForeignKey(Post, on_delete=models.CASCADE)
    categoryTr = models.ForeignKey(Category, on_delete=models.CASCADE)

class Comment(models.Model):
    commentPost = models.ForeignKey(Post, on_delete=models.CASCADE)
    commentUser = models.ForeignKey(User, on_delete=models.CASCADE)
    commentText = models.TextField()
    commentCreateData = models.DateTimeField(auto_now_add=True)
    rating = models.SmallIntegerField(default=0)

    def __str__(self):
        return self.commentUser.username

    def like(self):
        self.rating = self.rating + 1
        self.save()

    def dislike(self):
        self.rating = self.rating - 1
        self.save()

NewsPaper/news/forms.py
from django.forms import ModelForm
from .models import Post
from django import forms

# Создаём модельную форму
class PostForm(ModelForm):
# В класс мета, как обычно, надо написать модель, по которой будет строиться форма, и нужные нам поля. Мы уже делали что-то похожее с фильтрами
   class Meta:
       model = Post
       fields = ['author', 'type', 'title', 'articleText', 'description']
       widgets = {
         'author' : forms.Select(attrs={
           'class': 'form-control',
         }),
         'title' : forms.TextInput(attrs={
           'class': 'form-control',
           'placeholder': 'Enter Title post'
         }),
         'type' : forms.Select(attrs={
           'class': 'form-control',
         }),
         'description' : forms.Textarea(attrs={
           'class': 'form-control',
         }),
         'articleText': forms.Textarea(attrs={
            'class': 'form-control',
         }),
       }

NewsPaper/news/views.py
# from django.shortcuts import render
from django.views.generic import ListView, DetailView, View, UpdateView, CreateView, DeleteView
from .models import Post
from datetime import datetime
from django.shortcuts import render
from django.utils import timezone
from django.core.paginator import Paginator
from .filters import PostFilter
from .forms import PostForm
from django.urls import reverse_lazy

class PostsList(ListView):
    model = Post
    template_name = 'news/posts.html'
    context_object_name = 'posts'
    queryset = Post.objects.order_by('-createData')
    paginate_by = 10

    def get_context_data(self, **kwargs):
       context = super().get_context_data(**kwargs)
       context['time_now'] = timezone.localtime(timezone.now())
       context['value1'] = None
       context['filter'] = PostFilter(self.request.GET, queryset=self.get_queryset())
       context['form'] = PostForm()
       return context

    def post(self, request, *args, **kwargs):
        form = self.form_class(request.POST)  # создаём новую форму, забиваем в неё данные из POST-запроса
        if form.is_valid():  # если пользователь ввёл всё правильно и нигде не накосячил, то сохраняем новый товар
            form.save()
        return super().get(request, *args, **kwargs)

class PostDetailView(DetailView):
   template_name = 'news/post_detail.html'
   queryset = Post.objects.all()

# дженерик для создания объекта. Надо указать только имя шаблона и класс формы, который мы написали в прошлом юните. Остальное он сделает за вас
class PostCreateView(CreateView):
   template_name = 'news/post_create.html'
   form_class = PostForm

class PostDetail(DetailView):
    model = Post
    template_name = 'news/post.html'
    context_object_name = 'post'

# дженерик для редактирования объекта
class PostUpdateView(UpdateView):
   template_name = 'news/post_create.html'
   form_class = PostForm

   def get_object(self, **kwargs):
       id = self.kwargs.get('pk')
       return Post.objects.get(pk=id)

class PostDeleteView(DeleteView):
   template_name = 'news/post_delete.html'
   queryset = Post.objects.all()
   success_url = reverse_lazy('news:posts')

NewsPaper/news/templates/news/parts/paginator.html
{% if is_paginated %}

    {% if page_obj.has_previous %}
        <a href="?page=1">First</a>
        <a href="?page={{ page_obj.previous_page_number }}"><<<</a>
    {% endif %}

    {% for num in page_obj.paginator.page_range %}
        {% if page_obj.number == num %}
            <a>{{ num }}</a>
        {% elif num > page_obj.number|add:'-3' and num < page_obj.number|add:'3' %}
            <a href="?page={{ num }}">{{ num }}</a>
        {% endif %}
    {% endfor %}

    {% if page_obj.has_next %}
        <a href="?page={{ page_obj.next_page_number }}">>>></a>
        <a href="?page={{ page_obj.paginator.num_pages }}">Last</a>
    {% endif %}

{% endif %}

NewsPaper/news/templates/news/post.html
<!--  наследуемся от шаблона default.html -->
{% extends 'layout/default.html' %}
<!-- Название у нас будет proudcts -->
{% block title %}
Post
{% endblock title %}

{% block content %}

<h1>{{ post.title }}</h1>
<hr>
{{ post.createData|date:'d-m-Y h:m' }}
<hr>
{{ post.articleText }}

{% endblock content %}

NewsPaper/news/templates/news/post_create.html
{% extends 'layout/default.html' %}


{% block title %}
Post create
{% endblock title %}

{% block content %}

<h3>Post Information</h3>

<form method="POST">
 {% csrf_token %}
 {{ form }}
   <!-- Теперь нам нужна только готовая форма и кнопка -->
   <input class="btn btn-success" type="submit" value="Add">
</form>

{% endblock content %}

NewsPaper/news/templates/news/post_delete.html
{% extends 'layout/default.html' %}


{% block title %}
Post delete
{% endblock title %}

{% block content %}

<h3>Delete this post?</h3>
<div class="card">
 <div class="card-header">
   <h3>
     {{ post.name }}
   </h3>
   <div>
     Title: <span class="badge bg-info">{{ post.title }}</span>
     Type: <span class="badge bg-info">{{ post.get_type_display }}</span>
   </div>
 </div>
 <div class="card-body">
   {{ post.description }}
 </div>
</div>
<form method="POST">
 {% csrf_token %}
   <input class="btn btn-success" type="submit" value="Delete">
</form>

{% endblock content %}

NewsPaper/news/templates/news/post_detail.html
{% extends 'layout/default.html' %}


{% block title %}
Post
{% endblock title %}

{% block content %}
<div class="card">
 <div class="card-header">
   <h3>
     {{ post.name }}
   </h3>
   <div>
     Title: <span class="badge bg-info">{{ post.title }}</span>
     Type: <span class="badge bg-info">{{ post.get_type_display }}</span>
   </div>
 </div>
 <div class="card-body">
   {{ post.description }}
 </div>
</div>

{% endblock content %}

NewsPaper/news/templates/news/posts.html
<!--  наследуемся от шаблона default.html -->
{% extends 'layout/default.html' %}
{% load custom_filters %}
<!-- Название у нас будет proudcts -->
{% block title %}
Posts
{% endblock title %}

{% block content %}
    <h1>Все новости</h1>
    <h3> Общее количество новостей: {{ posts|length }} </h3>
    <hr>
    <h4>{{ time_now|date:'M d Y' }}</h4>
    {% if posts %}

    <form method="GET">
        {{ filter.form }}
        <!-- Форму от фильтров за нас сделает Django. А вот кнопку, увы, придётся делать самим -->
        <input class="btn btn-primary" type="submit" value="Найти">
    </form>

        <table class = "table">
            <tr>
                <th scope="col">
                    Заголовок
                </th>
                <th scope="col">
                    Дата публикации
                </th>
                <th scope="col">
                    Текст
                </th>

            </tr>

        {% for post in filter.qs %} <!-- Для каждого товара будет генерироваться новая строчка, т. е. новый HTML-код. При этом сам цикл работает точно так же, как и в python. product -- переменная цикла, т. е. наш товар, взятый из общего списка -->

            {{ person.anniversary.date|date:"M d, Y" }}
            <tr>
                <td>
                    <a href="{% url 'news:post_detail' post.id %}">
                    {{ post.title|censor }}
                    </a>
                </td>
                <td>
                    {{ post.createData|date:'d.m.Y' }}
                </td>
                <td>
                    {{ post.articleText|truncatechars:50|censor }}
                </td>
                <td>
                    <a href="{% url 'news:post_update' post.id %}">
                        Update
                    </a>
                    <a href="{% url 'news:post_delete' post.id %}">
                        Delete
                    </a>
                </td>
            </tr>
        {% endfor %}
        </table>

    {% include 'news/parts/paginator.html' %}

    {% else %}
        <h2>Новостей нет!</h2>
    {% endif %}


{% endblock content %}

NewsPaper/templates/layout/default.html
<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<meta http-equiv="X-UA-Compatible" content="ie=edge">
<meta name="Description" content="Enter your description here"/>
<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-rbsA2VBKQhggwzxH7pPCaAqO46MgnOM80zW1RWuH61DGLwZJEdK2Kadq2F9CUG65" crossorigin="anonymous">

<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.4/css/all.min.css">
<link rel="stylesheet" href="assets/css/style.css">
<script defer src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-kenU1KFdBIe4zVF0s0G1M5b4hcpxyD9F7jL+jjXkk+Q2h455rYXK/7HAuoJl+0I4" crossorigin="anonymous"></script>

<title>
{% block title %}
{% endblock title %}
</title>
</head>
<body>
{% include './parts/header.html' %}
<div class="container">
 {% block content %}
 {% endblock content %}
</div>

{% include './parts/footer.html' %}
</body>
</html>

NewsPaper/templates/layout/parts/footer.html
<footer class="footer mt-auto py-3 bg-light">
 <div class="container">
   <span class="text-muted">Place sticky footer content here.</span>
 </div>
</footer>

NewsPaper/templates/layout/parts/header.html
<header class="p-3 text-bg-dark">
 <div class="container">
   <div class="d-flex flex-wrap align-items-center justify-content-center justify-content-lg-start">
     <a href="/" class="d-flex align-items-center mb-2 mb-lg-0 text-white text-decoration-none">
       <svg class="bi me-2" width="40" height="32" role="img" aria-label="Bootstrap"><use xlink:href="#bootstrap"/></svg>
     </a>

     <ul class="nav col-12 col-lg-auto me-lg-auto mb-2 justify-content-center mb-md-0">
       <li><a href="#" class="nav-link px-2 text-secondary">Home</a></li>
       <li><a href="#" class="nav-link px-2 text-white">Features</a></li>
       <li><a href="#" class="nav-link px-2 text-white">Pricing</a></li>
       <li><a href="#" class="nav-link px-2 text-white">FAQs</a></li>
       <li><a href="#" class="nav-link px-2 text-white">About</a></li>
     </ul>

     <div class="text-end">
       <button type="button" class="btn btn-outline-light me-2">Login</button>
       <button type="button" class="btn btn-warning">Sign-up</button>
     </div>
   </div>
 </div>
</header>